### PR TITLE
Refactored print media

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
fixes https://github.com/mitodl/mitx-theme/issues/23
fixes https://github.com/mitodl/mitx-theme/pull/24

refactor on feedback from @jolyonb

screen shot 2017-08-25 at 3 48 11 pm

### CODE REVIEW

**Comment by shaidar** [comment]
@pdpinch This has been deployed to QA

**Comment by jolyonb** [comment]
👍 LGTM!

**Comment by pdpinch** [comment]
@shaidar @blarghmatey please deploy this theme change at your convenience (but not on 8/31 or 9/1!)

**Comment by jolyonb** [comment]
Hi folks, this looks like it hasn't been deployed into LMS at this stage?

**Pull request merged**
