### PR TITLE
Overriding register.underscore

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix https://github.mit.edu/mitx/Summer-2019/issues/17

#### What's this PR do?
Overrides the registration template with only offering to register with MIT Touchstone.

#### How should this be manually tested?
This should be deployed to qa for testing.

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@annagav I have tested the template.

**Comment by pdpinch** [comment]
@mitodl/devops can we deploy this to the QA stack?

**Comment by blarghmatey** [comment]
I checked out and deployed this change on current QA for testing

**Comment by blarghmatey** [comment]
:+1:

**Comment by annagav** [comment]
@blarghmatey was this working for you? I just get a blank page: https://mitx-qa.mitx.mit.edu/register

**Comment by blarghmatey** [comment]
Yeah, that's expected. QA next had the SAML integrations configured, but we don't have that on current QA or production so I would anticipate a blank page.

**Pull request merged**
