### PR TITLE
Remove invite students from studio

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/salt-ops/issues/398

#### What's this PR do?
It removes invite student from studio.

#### How should this be manually tested?
Ho to studio > course -> Schedule and details

#### Screenshot
**Before:**
screen shot 2017-09-20 at 4 29 15 pm

**After:**
screen shot 2017-09-20 at 4 35 21 pm

@pdpinch @mitodl/devops

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops please review and deploy, also cherry-pick to ficus-draft

**Comment by pdpinch** [comment]
To review, I'd like to do a diff between this file and the template that it's overriding. Where is the original template? 

@amir-qayyum-khan

**Comment by blarghmatey** [comment]
@pdpinch the path for the template will be  the same as it is in the theme. Think of the theme as an overlay on top of the existing templates in edX. As long as the paths match then the template from the theme gets applied in place of the original. In this case the path to the edX template is https://github.com/mitodl/edx-platform/blob/mitx/ficus/cms/templates/settings.html

**Comment by pdpinch** [comment]
@amir-qayyum-khan which template did you base this off of? When I compare it to the version that Tobias's pointed me to -- https://github.com/mitodl/edx-platform/blob/mitx/ficus/cms/templates/settings.html -- there are more differences than I expected. I don't want to accidentally pick up some post-ficus changes when we apply this override.

**Comment by amir-qayyum-khan** [comment]
let me look into this

**Comment by amir-qayyum-khan** [comment]
@pdpinch i double check, i picked correct template, this is good to go, you can run this on ficus as verify there is not issue

https://github.com/mitodl/edx-platform/blob/mitx/ficus/cms/templates/settings.html#L85
**Branch:** `mitx/ficus`

**Comment by pdpinch** [comment]
Okay. I set up a [diff between the two versions](https://gist.github.com/pdpinch/18bb3f1551c7e97fd65b02486b758228/revisions#diff-66a61e3a38d33964bc4f29dae6426b82) and I've convinced myself that this is the minimal change. 

👍

**Comment by amir-qayyum-khan** [comment]
Done @pdpinch

**Pull request merged**
