### PR TITLE
feat: update logo

### PR DESCRIPTION
**Pull request by asadali145**
#### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/3340

#### What's this PR do?
Updates the logo.

#### How should this be manually tested?

- Enable theming and use mitx-theme by following the [Readme](https://github.com/mitodl/mitx-theme)
- Add the following settings in the private.py
  - LMS_BASE_URL = "http://localhost:18000"
  - LOGO_URL_PNG_FOR_EMAIL = f"{LMS_BASE_URL}/static/mitx-theme/images/logo.png"
  - LOGO_URL = f"{LMS_BASE_URL}/static/mitx-theme/images/logo.svg"
  - LOGO_TRADEMARK_URL = f"{LMS_BASE_URL}/static/mitx-theme/images/mit-ol-logo.svg"
  - BULK_EMAIL_SEND_USING_EDX_ACE = True
- Verify the updated logos in the legacy theme and the MFEs
  - For any MFE, you will need to set the LOGO_URL and LOGO_TRADEMARK_URL in the .env.development
- Verify the logo in the Ace Emails

#### Screenshots (if appropriate)

Screenshot 2024-03-21 at 9 44 02 PM
Screenshot 2024-03-21 at 9 44 32 PM

### CODE REVIEW

**Review by arslanashraf7 — APPROVED** [review]
Looks good. 👍 Just one comment. 

- We will need to replace the favicon in the cms/static as well. While I was at it I noticed that our other themes also doesn't have a favicon for Studio unlike LMS. @pdpinch should we have the favicons for xPRO & MITx Online studio sites as well?

**Comment by asadali145** [comment]
@pdpinch Should we merge this PR? It will leak the new logos to the MITx Prod MFEs like the xPro. We have a PR in ol-infra to fix this issue but it will require a prod deployment https://github.com/mitodl/ol-infrastructure/pull/2270.

**Comment by pdpinch** [comment]
> @pdpinch Should we merge this PR? It will leak the new logos to the MITx Prod MFEs like the xPro. We have a PR in ol-infra to fix this issue but it will require a prod deployment https://github.com/mitodl/ol-infrastructure/pull/2270.

It's fine to leak the logos on Residential MITx. They are much less sensitive. 

That said, we should try to get @mitodl/devops to coordinate with Residential MITx about a release date soon so we don't have mismatched logos for too long.

**Comment by pdpinch** [comment]
> We will need to replace the favicon in the cms/static as well. While I was at it I noticed that our other themes also doesn't have a favicon for Studio unlike LMS. @pdpinch should we have the favicons for xPRO & MITx Online studio sites as well?

Yes, we should do that, but it's not a high-priority change. For example, it could wait on xPRO until the next release. on xPRO, it could even wait until the December 2024 release of Sycamore.

**Comment by asadali145** [comment]
> we should try to get @mitodl/devops to coordinate with Residential MITx about a release date soon so we don't have mismatched logos for too long.

@blarghmatey Could you please take care of a question for the DevOps by Peter in https://github.com/mitodl/mitx-theme/pull/142#issuecomment-2025093925. Also, You merged the related ol-infra PR https://github.com/mitodl/ol-infrastructure/pull/2270 before this theme PR. I have merged this theme PR today. How is this going to be deployed on the staging/QA environments? Is it auto or do we need to trigger?

**Comment by blarghmatey** [comment]
It will be automatically deployed to the CI environment. From there we will propagate it to QA this morning.

In terms of the residential release, we can work with that team to get the release deployed, possibly on Monday.

**Pull request merged**
