### PR TITLE
Use the text file body template for instructor enrollment emails

### LINKED ISSUE #97: Revert enrollment email template
When an instructor manually enrolls or unenrolls a student from the[ instructor dash,](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.201915+2019_Summer/instructor#view-membership) they can choose to send an automated email. 

The current production style of the email looks like this: 
screenshot 2019-05-20 13 36 34

The QA email looks like this:
screenshot 2019-05-20 13 35 35

All things being equal, the residential team would prefer the current production template, and not the version generated on the QA server.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #97 

#### What's this PR do?
Override the html body template for `enrollenrolled` and `allowenrolled` emails.

#### How should this be manually tested?
As an instructor enroll a student in a course, the student should receive an email.

### CODE REVIEW

**Comment by pdpinch** [comment]
@tasawernawaz this is a bit of a departure, but can you review this theme change for the **Residential MITx** theme?

For a case like this, you could test with the same Ironwood branch that we're using for MIT xPRO.

**Comment by tasawernawaz** [comment]
@pdpinch If thats ok, I will review this tomorrow. It requires to change my env vars to this theme.

**Comment by pdpinch** [comment]
@annagav please merge

@mitodl/devops please deploy to residential QA for review after this is merged.

**Comment by annagav** [comment]
@blarghmatey was this also deployed to QA?

**Comment by blarghmatey** [comment]
Yes, everything in the `ironwood` branch should be on QA (mitx-qa.mitx.mit.edu)

**Comment by annagav** [comment]
I verified that this is working on QA.

**Pull request merged**
