### PR TITLE
Revert "Removed PARTNER_SUPPORT_EMAIL from cms template"

### LINKED ISSUE #90: Ironwood: revert Removed PARTNER_SUPPORT_EMAIL from cms template
I don't think we need this theme override anymore, as long as we set `PARTNER_SUPPORT_EMAIL` to the Residential MITx support email address. 

We should probably remove sock.html altogether. If that's too drastic we can just revert https://github.com/mitodl/mitx-theme/commit/98109e59bab98e104820e4bef8f1faa519940a22

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #90

#### What's this PR do?
This reverts commit 98109e59bab98e104820e4bef8f1faa519940a22.

#### How should this be manually tested?
(Required)

### CODE REVIEW

**Comment by pdpinch** [comment]
What happens if we remove the sock.html from the theme altogether?

**Comment by annagav** [comment]
Here is a screenshot with the changes reverted:
screen shot 2018-11-27 at 9 57 24 am

**Comment by annagav** [comment]
Here is with the the final removed from themes:
screen shot 2018-11-27 at 10 18 41 am

I think the difference is in the link to 'https://partners.edx.org'

**Comment by pdpinch** [comment]
We should remove sock.html altogether. I'm closing this in favor of #94 but we don't need to merge it until we start working on the summer release, Ironwood.

**Pull request closed without merging**
